PicPop/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PagedList;
using PicPop.Models;
using PicPop.BusinessLogic;
using PicPop.BusinessLogic.Models;
using PicPop.BusinessLogic.Utils;

namespace PicPop.Controllers
{
    public class ImageController : Controller
    {
        // GET: Images
        public ActionResult Index(int? id, int? page)
        {
            PicPopImagesHelper imagesHelper = new PicPopImagesHelper();
            List<PicPopImage> lst = imagesHelper.GetShop(User.Identity.GetUserId(), id);

            IEnumerable<ImagesDetailsViewModels> lstImages = lst.Select(x => new ImagesDetailsViewModels()
            {
                Id = x.Id.ToString(),
                Name = x.Name,
                Amount = x.Amount,
                Blob = CloudStorageManagerHelper.GetUrlInfo(
                        x.BlobFiles.First(y => y.Container.Equals((int) BlobFileType.ImagesWaterMark))),
                IsMine = true
            }).AsEnumerable();

            
            ImageSearchViewModel model = new ImageSearchViewModel()
            {
                Categories = PicPop.Helper.CategoriesHelper.GetCategoriesSelectedItems(),
                List = lstImages.ToPagedList(page??1, 12),
                Id = id
            };

            return View(model);
        }


        // GET: Images/Details/5
        public ActionResult Details(int id)
        {
            var imageHelper = new PicPopImagesHelper();
            PicPopImage image = imageHelper.Details(id);

            // Check if the image exist and if the image is relationship with the user
            if (image == null) //|| !image.UserId.Equals(User.Identity.GetUserId()))
                return RedirectToAction("Index");

            string userId = User.Identity.GetUserId();
            int containerId = (int) BlobFileType.ImagesWaterMark;
            if (!string.IsNullOrEmpty(userId) &&
                (image.UserId.Equals(userId) ||
                 (image.TransactionItems != null && image.TransactionItems.Any(y=>y.Transaction.UserId.Equals(userId)))))
                containerId = (int) BlobFileType.ImagesOriginal;

            ImagesDetailsViewModels model = new ImagesDetailsViewModels()
            {
                Id = image.Id.ToString(),
                Name = image.Name,
                Amount = image.Amount,
                //Blob = CloudStorageManagerHelper.GetUrlInfo(BlobFileType.ImagesOriginal, image.BlobFiles.First().BlobKey),
                Blob = CloudStorageManagerHelper.GetUrlInfo(image.BlobFiles.First(y => y.Container.Equals(containerId))),
                Category = image.CategoryId.HasValue ? image.Category.Name : "None",
                IsMine = image.UserId.Equals(User.Identity.GetUserId())
            };

            return View(model);
        }


        [Authorize]
        public ActionResult MyImages()
        {
            PicPopImagesHelper images = new PicPopImagesHelper();
            List<PicPopImage> lst = images.GetMyImagesList(User.Identity.GetUserId());

            IEnumerable<ImagesDetailsViewModels> model = lst.Select(x => new ImagesDetailsViewModels()
            {
                Id = x.Id.ToString(),
                Name = x.Name,
                Amount = x.Amount,
                Blob = CloudStorageManagerHelper.GetUrlInfo(x.BlobFiles.FirstOrDefault(y=>y.Container.Equals((int)BlobFileType.ImagesOriginal))),
                IsMine = true
            }).AsEnumerable();
            return View(model);
        }

        // GET: Images/Create
        [Authorize]
        public ActionResult Create()
        {
            var model = new ImagesCreateViewModels()
            {
                Categories = PicPop.Helper.CategoriesHelper.GetCategoriesSelectedItems()
            };

            return View(model);
        }


        // POST: Images/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(ImagesCreateViewModels images)
        {
            
            if (ModelState.IsValid)
            {
                string userId = User.Identity.GetUserId();
                int categoryId;
                if (!int.TryParse(images.CategoryId, out categoryId))
                    categoryId = 0;
                
                var lstBlobs = new PicPop.Helper.PicPopImagesHelper().CreateImage(userId, images.File);
                
                PicPopImage image = new PicPopImage
                {
                    Name = images.Name,
                    Amount = images.Amount,
                    DtAdded = DateTime.Now,
                    UserId = userId,
                    BlobFiles = lstBlobs,
                    CategoryId = categoryId == 0 ? (int?) null : categoryId,
                    CreatedBy = userId
                };

                var imageHelper = new PicPopImagesHelper();
                imageHelper.Add(image);

                return RedirectToAction("MyImages");
            }

            images.Categories = PicPop.Helper.CategoriesHelper.GetCategoriesSelectedItems();
            return View(images);
        }

        // GET: Images/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            var imageHelper = new PicPopImagesHelper();
            PicPopImage image = imageHelper.Details(id);

            // Check if the image exist and if the image is relationship with the user
            if (image == null || !image.UserId.Equals(User.Identity.GetUserId()))
                return RedirectToAction("Index");

            ImagesEditViewModels model = new ImagesEditViewModels()
            {
                Name = image.Name,
                Amount = image.Amount,
                CategoryId = image.CategoryId.ToString(),
                Categories = PicPop.Helper.CategoriesHelper.GetCategoriesSelectedItems(),
                //Blob = CloudStorageManagerHelper.GetUrlInfo(BlobFileType.ImagesOriginal, image.BlobFiles.First().BlobKey)
                Blob = CloudStorageManagerHelper.GetUrlInfo(image.BlobFiles.First())
            };

            return View(model);
        }

        // POST: Images/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, ImagesEditViewModels model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int categoryId;
                    var imageHelper = new PicPopImagesHelper();
                    PicPopImage image = imageHelper.FindById(id);

                    // Check if the image exist and if the image is relationship with the user
                    if (image == null || !image.UserId.Equals(User.Identity.GetUserId()))
                        return RedirectToAction("Index");

                    image.Name = model.Name;
                    image.Amount = model.Amount;
                    image.DtModified = DateTime.Now;
                    image.UserId = User.Identity.GetUserId();

                    if (!int.TryParse(model.CategoryId, out categoryId))
                        categoryId = 0;
                    image.CategoryId = categoryId == 0 ? (int?) null : categoryId;

                    imageHelper.Update(image);

                    return RedirectToAction("MyImages");
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }



        //// GET: Images/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Images/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

PicPop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Management;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PicPop.BusinessLogic;
using PicPop.BusinessLogic.Utils;
using PicPop.Models;

namespace PicPop.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            string userId = GetCartId();

            var cart = ShoppingCartHelper.GetCart(userId);

            if(cart == null)
                return RedirectToAction("Index", "Home");

            var model = cart.ListItems.Select(x=> new SummaryCartViewModel()
            {
                Id = x.Id,
                Name = x.Name,
                Amount = x.Amount
            }).AsEnumerable();
            
            return View(model);
        }


        // GET: /ShoppingCart/Add/1
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Add(int id)
        {
            string userId = GetCartId();
            
            ShoppingCartHelper shopCartHelper = new ShoppingCartHelper();
            int numItems = shopCartHelper.Add(id, userId);

            // Display the confirmation message
            var result = new AddToCartViewModel()
            {
                NumItems = numItems.ToString()
            };

            return Json(result);
        }

        
        [Authorize]
        public ActionResult Buy()
        {
            string userId = string.Empty;

            if (User.Identity.IsAuthenticated)
                userId = User.Identity.GetUserId();
            else
                userId = GetCartId();

            var cart = ShoppingCartHelper.GetCart(userId);

            if (cart == null || !cart.ListItems.Any())
                return RedirectToAction("Index", "Home");
            
            var lst = cart.ListItems.Select(x => new TransactionItem()
            {
                ImageId = x.Id,
                Value = x.Amount
            }).ToList();
            
            var transactionHelper = new TransactionsHelper();
            // TypeId = true because is a Buy. We generate the sell with a trigger in the DB
            var transaction = new Transaction()
            {
                UserId = userId,
                DtAdded = DateTime.Now,
                CreatedBy = userId,
                Amount = cart.TotalAmount,
                TransactionItems = lst,
                TypeId = true
            };
            transactionHelper.Add(transaction);


            return RedirectToAction("Index","Transaction");
        }


        // GET: /ShoppingCart/Add/1
        [HttpGet]
        public ActionResult Remove(int id)
        {
            string userId = GetCartId();

            ShoppingCartHelper shoppingCartHelper = new ShoppingCartHelper();
            shoppingCartHelper.Delete(id, userId);
            
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult RemoveAll()
        {
            string userId = GetCartId();

            ShoppingCartHelper shoppingCartHelper = new ShoppingCartHelper();
            shoppingCartHelper.DeleteAll(userId);

            return RedirectToAction("Index");
        }


        private string GetCartId()
        {
            if (User.Identity.IsAuthenticated)
            {
                Session["CartId"] = User.Identity.GetUserId();
                return User.Identity.GetUserId();
            }

            return PicPop.Helper.ShoppingCartHelper.GetCartId();
        }
    }
}

PicPop/Views/Shared/_Layout.cshtml
@using PicPop.BusinessLogic
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1,user-scalable=no ">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href='http://fonts.googleapis.com/css?family=Dosis:200,400,600' rel='stylesheet' type='text/css'>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container">

        <div class="text-warning ">
            Dublin @Html.Action("GetWeather", "Home")
        </div>
       

        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="navbar-brand" style="padding-top: 11.5px">
                        <a href="@Url.Action("Index", "Home")">
                            <img src="/Content/Images/PicPop.jpg" class="img img-responsive img-circle pull-right" alt="Logo" />
                            <h4 class="alert alert-info pull-left " style="padding:5px; border-radius:13px; margin-right:3px;">PicPop  Image Repository</h4>
                        </a>

                    </div>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   
                  

                </div>
              
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    

                    <ul class="nav navbar-nav">


                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink(" All Images", "Index", "Image")</li>


                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("My Images", "MyImages", "Image")</li>
                        }
                        @if (User.IsInRole(RoleType.Admin.ToString()))
                        {
                            <li>
                                @Html.ActionLink("Categories", "Index", "Categories")
                            </li>
                            <li>
                                @Html.ActionLink("Admin", "Index", "Manage")
                            </li>
                        }
                        @if (Request.IsAuthenticated && ViewBag.IsTransaction)
                        {
                            <li>
                                @Html.ActionLink("Transactions", "Index", "Transaction")
                            </li>
                        }

                        @if (ViewBag.ShopCartNumElements == 0)
                        {
                            <li style="display: none">
                                <a href="@Url.Action("Index", "ShoppingCart")">
                                    <label id="CartNumElements">@ViewBag.ShopCartNumElements </label>
                                    <span class="text-center"> </span>  <i class="glyphicon glyphicon-shopping-cart "></i>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a href="@Url.Action("Index", "ShoppingCart")"> 
                                    <label id="CartNumElements"><span class="label label-danger"> @ViewBag.ShopCartNumElements</span></label>
                                    <span class="glyphicon glyphicon-shopping-cart "></span>
                                </a>
                            </li>
                        }


                    </ul>
                    


                    <div >
                       
                        @Html.Partial("_LoginPartial")

                    </div>
                   
                </div>
               
            </div>
        </nav>
    </div>

    <div class="container">


        @RenderBody()

    </div>
    <div class="container">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <!-- Copyright information -->
                        <div class="fpadd text-center">
                            <span class="text-info">   National Collage of Ireland</span> </br>&copy; @DateTime.Now.Year
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/easing")*@
    @Scripts.Render("~/bundles/bootstrap")
    @*@Scripts.Render("~/bundles/ddlevelsmenu")*@
    @Scripts.Render("~/bundles/flexslider")
    @Scripts.Render("~/bundles/isotope")
    @Scripts.Render("~/bundles/jquery.prettyPhoto")
    @*@Scripts.Render("~/bundles/custom")*@

    @Scripts.Render("~/bundles/misScripts")


    @RenderSection("scripts", required: false)
</body>

</html>